=== gr0x0/Caravela_BDT_v1.0/bin/CarroSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<car:schema xmlns:car="http://www.w3.org/2001/XMLSchema">
	<!--targetNamespace="http://www.motionmedia.com/CarrosSchema" > -->

	<!-- definition of simple elements -->

	<car:element name="lat0" type="car:double" />
	<car:element name="latF" type="car:double" />
	<car:element name="lon0" type="car:double" />
	<car:element name="lonF" type="car:double" />
	<car:element name="impressao" type="car:string" />

	<!-- definition of attributes -->

	<car:attribute name="chassiCarro" type="car:string" />
	<car:attribute name="idCarro" type="car:string" />
	<car:attribute name="idLinha" type="car:string" />
	<car:attribute name="idZona" type="car:string" />

	<!-- definition of complex elements -->

	<car:element name="listaImpressoes">
		<car:complexType>
			<car:sequence>
				<car:element ref="impressao" maxOccurs="12" minOccurs="2" />
			</car:sequence>
		</car:complexType>
	</car:element>

	<car:element name="zona">
		<car:complexType>
			<car:sequence>
				<car:element ref="lat0" maxOccurs="1" minOccurs="1" />
				<car:element ref="latF" maxOccurs="1" minOccurs="1" />
				<car:element ref="lon0" maxOccurs="1" minOccurs="1" />
				<car:element ref="lonF" maxOccurs="1" minOccurs="1" />
				<car:element ref="listaImpressoes" maxOccurs="1"
					minOccurs="1" />
			</car:sequence>
			<car:attribute ref="idZona" use="required" />
		</car:complexType>
	</car:element>

	<car:element name="linhaCarro">
		<car:complexType>
			<car:sequence>
				<car:element ref="zona" maxOccurs="unbounded" minOccurs="1" />
			</car:sequence>
			<car:attribute ref="idLinha" use="required" />
		</car:complexType>
	</car:element>

	<car:element name="carroInfo">
		<car:complexType>
			<car:sequence>
				<car:element ref="linhaCarro" />
			</car:sequence>
			<car:attribute ref="idCarro" use="required" />
			<car:attribute ref="chassiCarro" use="required" />
		</car:complexType>
	</car:element>

</car:schema>

=== gr0x0/Caravela_BDT_v1.0/resources/CarroExemplo.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New document created with EditiX at Wed Jun 17 23:30:49 BRT 2015 -->


<carroInfo 

xmlns="http://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3schools.com CarroSchema.xsd"
idCarro="MARCOPOLO0032"
chassiCarro="KJNDF875KNS764HD00001">
	<linhaCarro idLinha="645">
		<zona idZona="GAVEA03">
			<lat0>-22.931859</lat0>
			<latF>-22.846682</latF>
			<lon0>-43.496107</lon0>
			<lonF>-43.393895</lonF>
			<listaImpressoes>
				<impressao>CocaCola_13_02_16</impressao>
				<impressao>Pepsi_15_01_16</impressao>
				<impressao>Sprite_10_12_15</impressao>
				<impressao>FantaLaranja_01_01_16</impressao>
			</listaImpressoes>
		</zona>
		<zona idZona="GAVEA04">
			<lat0>-23.000000</lat0>
			<latF>-22.931859</latF>
			<lon0>-43.496107</lon0>
			<lonF>-43.393895</lonF>
			<listaImpressoes>
				<impressao>Flamengo_22_11_15</impressao>
				<impressao>Fluminense_10_01_15</impressao>
				<impressao>Botafogo_17_01_16</impressao>
				<impressao>Vasco_25_12_15</impressao>
			</listaImpressoes>
		</zona>
		<zona idZona="LEBLON01">
			<lat0>-23.914823</lat0>
			<latF>-22.863717</latF>
			<lon0>-43.393895</lon0>
			<lonF>-43.257612</lonF>
			<listaImpressoes>
				<impressao>CasaDaEmpada_02_12_15</impressao>
				<impressao>Xerox_27_11_15</impressao>
				<impressao>Morning_14_12_15</impressao>
				<impressao>LABGRAD_03_01_16</impressao>
				<impressao>Carga_Nobre_22_12_15</impressao>
				<impressao>Pilotis_12_01_16</impressao>
				<impressao>Bosque_01_01_16</impressao>
				<impressao>Leme_10_01_16</impressao>
				<impressao>Fastway_09_01_16</impressao>
			</listaImpressoes>
		</zona>
	</linhaCarro>
</carroInfo>
