=== gr0x0/Caravela_BDT_v1.0/resources/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Documento XSD v1.0 -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.w3schools.com"
xmlns="http://www.w3schools.com"
elementFormDefault="qualified">

<xs:element name="zonas">
	<xs:attribute name="id" type="xs:string" use="required"/>
	<xs:complexType>
		<xs:sequence>
		
			<xs:element name="zona" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
					
            			<xs:element name="lat0" type="xs:decimal" default="0.0"/>
      					<xs:element name="latF" type="xs:decimal" default="0.0"/>
      					<xs:element name="lon0" type="xs:decimal" default="0.0"/>
      					<xs:element name="lonF" type="xs:decimal" default="0.0"/>
      					
    				    <xs:element name="impressoes">
      				  		<xs:complexType>
          						
       			    	 			<xs:element name="impressao" type="xs:string" maxOccurs="unbounded"/>
       			    	 			
        					</xs:complexType>
        				</xs:element>
        					
      				</xs:sequence>
        		</xs:complexType>
     		</xs:element>
    	</xs:sequence>
	</xs:complexType>
</xs:element>

</xs:schema>

=== gr0x0/Caravela_BDT_v1.0/bin/zonas.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New XML document created with EditiX XML Editor (http://www.editix.com) at Thu Jun 04 15:31:58 BRT 2015 -->


<zonas xmlns="http://www.w3schools.com"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.w3schools.com data//schema.xsd">
           
           <zona id="GAVEA03">
           		<lat0>-22.931859</lat0>
           		<latF>-22.846682</latF>
           		<lon0>-43.496107</lon0>
           		<lonF>-43.393895</lonF>
           		<impressoes>
           			<impressao>CocaCola_13_02_16</impressao>
           			<impressao>Pepsi_15_01_16</impressao>
           			<impressao>Sprite_10_12_15</impressao>
           			<impressao>FantaLaranja_01_01_16</impressao>
           		</impressoes>           
           </zona>
                 
</zonas>

=== gr0x0/Caravela_BDT_v1.0/resources/zonas.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New XML document created with EditiX XML Editor (http://www.editix.com) at Thu Jun 04 15:31:58 BRT 2015 -->


<zonas xmlns="http://www.w3schools.com"
 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.w3schools.com data//schema.xsd">
           
           <zona id="GAVEA03">
           		<lat0>-22.931859</lat0>
           		<latF>-22.846682</latF>
           		<lon0>-43.496107</lon0>
           		<lonF>-43.393895</lonF>
           		<impressoes>
           			<impressao>CocaCola_13_02_16</impressao>
           			<impressao>Pepsi_15_01_16</impressao>
           			<impressao>Sprite_10_12_15</impressao>
           			<impressao>FantaLaranja_01_01_16</impressao>
           		</impressoes>           
           </zona>
           
           <zona id="GAVEA04">
           		<lat0>-23.000000</lat0>
           		<latF>-22.931859</latF>
           		<lon0>-43.496107</lon0>
           		<lonF>-43.393895</lonF>
           		<impressoes>
           			<impressao>Flamengo_22_11_15</impressao>
           			<impressao>Fluminense_10_01_15</impressao>
           			<impressao>Botafogo_17_01_16</impressao>
           			<impressao>Vasco_25_12_15</impressao>
           		</impressoes>           
           </zona>
           
           <zona id="LEBLON01">
           		<lat0>-23.914823</lat0>
           		<latF>-22.863717</latF>
           		<lon0>-43.393895</lon0>
           		<lonF>-43.257612</lonF>
           		<impressoes>
           			<impressao>CasaDaEmpada_02_12_15</impressao>
           			<impressao>Xerox_27_11_15</impressao>
           			<impressao>Morning_14_12_15</impressao>
           			<impressao>LABGRAD_03_01_16</impressao>
           			<impressao>Carga_Nobre_22_12_15</impressao>
           			<impressao>Pilotis_12_01_16</impressao>
           			<impressao>Bosque_01_01_16</impressao>
           			<impressao>Leme_10_01_16</impressao>
           			<impressao>Fastway_09_01_16</impressao>
           		</impressoes>           
           </zona>
                 
</zonas>
